### ISSUE TITLE
VALUE.ARRAY type can only get the last value

### ISSUE THREAD

**Issue by ebookbug** [runner-mei/gowbem#5]
Thanks for your share on this module.

When I try to use it,I found that the value array type can only return the last value

The origion value is Dedicated = {3, 15}，I only get 15 
&{{ PROPERTY.ARRAY} Dedicated uint16 0  false   [] [{15 <nil>}]}

`
insts, err := conn.EnumerateInstances(namespace, "CIM_ComputerSystem", false, false, false, false, nil)

	if err != nil {
		log.Error(err)
	}

	for _, inst := range insts {
		log.Info(inst.GetName())

		propDedicated := inst.GetInstance().GetPropertyByName("Dedicated")

		fmt.Println(propDedicated)

		for _, d := range propDedicated.GetValue().([]interface{}) {
			fmt.Println(d.(string))
		}

		for _, prop := range inst.GetInstance().GetProperties() {
			fmt.Print(prop.GetName(), ":", prop.GetValue(), "  ")
		}
		fmt.Println()
	}`

发现注释有中文，猜测你也是国内的，有没有QQ联系一下，我的29956298

**Comment by ebookbug** [comment]
I fixed it by these code,I will pull a new request  tomorrow

type CimValueArray struct {
	Values []string `xml:"VALUE"`
}

**Comment by runner-mei** [comment]
你能将这个请求和应答的 xml 发给我么？

**Comment by runner-mei** [comment]
你看是不是已解决

**Comment by ebookbug** [comment]
解决了，谢谢。
